### ISSUE TITLE
C Code in Your Ruby Code

### ISSUE THREAD

**Issue by burtlo** [burtlo/metro#1]
```
Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/property.rb:217:in `require_relative': /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:49: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '(' (SyntaxError)
      void drawRot(double x, double y, ZPos z,
                                     ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:49: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
      void drawRot(double x, double y, ZPos z,
                                             ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:50: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
          double angle, double centerX = 0.5, double centerY = 0.5,
                      ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:50: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
          double angle, double centerX = 0.5, double centerY = 0.5,
                                      ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:50: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
          double angle, double centerX = 0.5, double centerY = 0.5,
                                                            ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:51: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
          double factorX = 1, double factorY = 1,
                        ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:51: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
          double factorX = 1, double factorY = 1,
                                            ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:52: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
          Color c = Color::WHITE,
                 ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:53: syntax error, unexpected tIDENTIFIER, expecting keyword_do or '{' or '('
          AlphaMode mode = amDefault) const;
                        ^
/Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/scale_property.rb:53: syntax error, unexpected ')', expecting keyword_end
          AlphaMode mode = amDefault) const;
                                     ^
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/properties/property.rb:217:in `<top (required)>'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/model.rb:2:in `require_relative'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro/models/model.rb:2:in `<top (required)>'
    from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `block in require'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `block in load_dependency'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:591:in `new_constants_in'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/activesupport-3.0.0/lib/active_support/dependencies.rb:239:in `require'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/lib/metro.rb:33:in `<top (required)>'
    from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/burtlo/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/site_ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/gems/metro-0.3.0/bin/metro:9:in `<top (required)>'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/bin/metro:19:in `load'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/bin/metro:19:in `<main>'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/bin/ruby_noexec_wrapper:14:in `eval'
    from /Users/burtlo/.rvm/gems/ruby-1.9.2-p320@gaming/bin/ruby_noexec_wrapper:14:in `<main>'
```

**Comment by rbxbx** [comment]
Looks like it stems from this bit of code

```
  void drawRot(double x, double y, ZPos z,
      double angle, double centerX = 0.5, double centerY = 0.5,
      double factorX = 1, double factorY = 1,
      Color c = Color::WHITE,
      AlphaMode mode = amDefault) const;
```

**Comment by burtlo** [comment]
Yeah that was previously some example code from Gosu that got caught in my copy-paste buffer and was written out to the file.

All fixed now, re-released a new version. Thanks for bringing this to my attention.
